---
# Common nginx configuration for all servers
nginx_enable: true
nginx_cleanup_config: true
nginx_cleanup_config_backup_location: "/tmp/"

# Main nginx configuration
nginx_main_template_enable: true
nginx_main_template:
  template_file: nginx.conf.j2
  conf_file_name: nginx.conf
  conf_file_location: /etc/nginx/
  user: www-data
  worker_processes: "{{ nginx_worker_processes | default('auto') }}"
  worker_connections: "{{ nginx_worker_connections | default(1024) }}"
  keepalive_timeout: 65
  server_tokens: "off"
  gzip: true
  access_log_format:
    - name: main
      format: |
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"'

# HTTP configuration
nginx_http_template_enable: true
nginx_http_template:
  - template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      - listen:
          - port: 80
            default_server: true
        server_name: "_"
        access_log:
          - name: main
            location: /var/log/nginx/access.log
        error_log:
          - location: /var/log/nginx/error.log
            level: warn
        root: /var/www/html
        index: index.html index.htm
        location:
          - location: /
            try_files: $uri $uri/ =404
          - location: /health
            return: 200 "OK"
            add_header: "Content-Type text/plain"

# Security headers
nginx_http_template_security_headers:
  - name: X-Frame-Options
    value: DENY
  - name: X-Content-Type-Options
    value: nosniff
  - name: X-XSS-Protection
    value: "1; mode=block"
