---
# Collections
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 10.7.0

# Roles
roles:
  - name: nginxinc.nginx
    version: "0.25.0"
  - name: nginxinc.nginx_config
    version: "0.7.1"
