---
# UAT-specific nginx configuration
nginx_worker_processes: 2
nginx_worker_connections: 1024

# UAT settings (less aggressive caching and logging for debugging)
nginx_main_template:
  template_file: nginx.conf.j2
  conf_file_name: nginx.conf
  conf_file_location: /etc/nginx/
  user: www-data
  worker_processes: "{{ nginx_worker_processes }}"
  worker_connections: "{{ nginx_worker_connections }}"
  keepalive_timeout: 65
  server_tokens: "on" # Enable for debugging in UAT
  gzip: true
  access_log_level: debug

# UAT logging with more details for debugging
nginx_access_log_format:
  - name: main
    format: |
      '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for" '
      'rt=$request_time'
