---
all:
  children:
    nginx_servers:
      hosts:
        uat-web-01:
          ansible_host: 135.125.245.225
          ansible_user: debian
      vars:
        environment: uat
        nginx_worker_processes: 2
        nginx_worker_connections: 1024
