---
all:
  children:
    nginx_servers:
      hosts:
        prod-web-01:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
        prod-web-02:
          ansible_host: 10.0.1.11
          ansible_user: ubuntu
        prod-web-03:
          ansible_host: 10.0.1.12
          ansible_user: ubuntu
      vars:
        environment: production
